// app/dashboard/reports/finance/page.jsx
import { getFinancialSummary } from "@/lib/finance";
import PrintButton from "@/app/components/PrintButton";

export default async function FinanceReport({ searchParams }) {
  const { from, to } = await searchParams;
  const start = from ? new Date(from) : new Date(new Date().setDate(1)); // Start of month
  const end = to ? new Date(to) : new Date();

  const summary = await getFinancialSummary(start, end);

  return (
    <div className="p-8 bg-gray-50 dark:bg-gray-900 min-h-screen print:bg-white">
      <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 shadow-lg rounded-xl p-10 print:shadow-none">
        {/* Header */}
        <div className="flex justify-between border-b pb-6 mb-8">
          <div>
            <h1 className="text-2xl font-bold text-blue-800">
              Financial Statement
            </h1>
            <p className="text-sm text-gray-500">
              Period: {start.toLocaleDateString()} - {end.toLocaleDateString()}
            </p>
          </div>
          <PrintButton />
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-3 gap-6 mb-10">
          <div className="p-4 bg-green-50 border-t-4 border-green-500 rounded">
            <p className="text-xs text-green-600 font-bold uppercase">
              Total Income
            </p>
            <p className="text-2xl font-black text-green-700">
              ৳{summary.income}
            </p>
          </div>
          <div className="p-4 bg-red-50 border-t-4 border-red-500 rounded">
            <p className="text-xs text-red-600 font-bold uppercase">
              Total Expense
            </p>
            <p className="text-2xl font-black text-red-700">
              ৳{summary.expense}
            </p>
          </div>
          <div className="p-4 bg-blue-50 border-t-4 border-blue-500 rounded">
            <p className="text-xs text-blue-600 font-bold uppercase">
              Net Fund
            </p>
            <p
              className={`text-2xl font-black ${
                summary.netFund >= 0 ? "text-blue-700" : "text-red-700"
              }`}
            >
              ৳{summary.netFund}
            </p>
          </div>
        </div>

        {/* Detailed Breakdown */}
        <div className="space-y-4">
          <h2 className="font-bold border-b pb-2">Analysis</h2>
          <div className="flex justify-between py-2 border-b border-dashed">
            <span>Customer Bill Collections</span>
            <span className="text-green-600 font-medium">
              + ৳{summary.income}
            </span>
          </div>
          <div className="flex justify-between py-2 border-b border-dashed">
            <span>Employee Salary Paid</span>
            <span className="text-red-600 font-medium">
              - ৳{/* Add variable here */}
            </span>
          </div>
          <div className="flex justify-between py-2 border-b border-dashed">
            <span>General Office Expenses</span>
            <span className="text-red-600 font-medium">
              - ৳{/* Add variable here */}
            </span>
          </div>
        </div>

        <p className="mt-20 text-center text-xs text-gray-400 italic">
          Report Generated by {process.env.NEXT_PUBLIC_APP_NAME} on{" "}
          {new Date().toLocaleString()}
        </p>
      </div>
    </div>
  );
}
